services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: studentserver
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: studentdb
      DB_PORT: 5432
    networks:
      - backend   

  db:
    image: postgres:latest
    container_name: studentdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: